BakeCake/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.urls import path

from cake.forms import UserLoginForm
from cake import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.index, name='index'),
    path('login/', views.LoginUserView.as_view(authentication_form=UserLoginForm), name='login'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
    path('signup/', views.SignupUserView.as_view(), name='signup'),
    path('advanced/', views.advanced_info, name='advanced_info'),
    path('confirm/', views.confirm, name='confirm'),
    path('account/', views.account, name='account'),
    path('cancel_order/<int:order_id>', views.cancel_order, name='cancel_order')
] + static(settings.DOCS_URL, document_root=settings.DOCS_DIR)

cake/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxLengthValidator
from django.db import models
from django.utils import timezone

from phonenumber_field.modelfields import PhoneNumberField


STATUS = (
    ('PENDING', 'Заявка обрабатывается'),
    ('COOKED', 'Торт готовится'),
    ('EN_ROUTE', 'Торт в пути'),
    ('COMPLETED', 'Выполнен'),
    ('CANCELED', 'Отменен'),
)


class Level(models.Model):
    levels_count = models.PositiveSmallIntegerField(
        'число уровней',
    )
    price = models.DecimalField(
        'цена',
        max_digits=8,
        decimal_places=2,
    )

    class Meta:
        verbose_name = 'число уровней'
        verbose_name_plural = 'числа уровней'

    def __str__(self):
        return f'{self.levels_count} уровней'


class Shape(models.Model):
    figure = models.CharField(
        'фигура',
        max_length=20,
    )
    price = models.DecimalField(
        'цена',
        max_digits=8,
        decimal_places=2,
    )

    class Meta:
        verbose_name = 'форма'
        verbose_name_plural = 'формы'

    def __str__(self):
        return self.figure


class Topping(models.Model):
    name = models.CharField(
        'название',
        max_length=20,
    )
    price = models.DecimalField(
        'цена',
        max_digits=8,
        decimal_places=2,
    )

    class Meta:
        verbose_name = 'топпинг'
        verbose_name_plural = 'топпинги'

    def __str__(self):
        return self.name


class Berry(models.Model):
    name = models.CharField(
        'название',
        max_length=20,
    )
    price = models.DecimalField(
        'цена',
        max_digits=8,
        decimal_places=2,
    )

    class Meta:
        verbose_name = 'ягода'
        verbose_name_plural = 'ягоды'

    def __str__(self):
        return self.name


class AdditionalIngredient(models.Model):
    name = models.CharField(
        'название',
        max_length=20,
    )
    price = models.DecimalField(
        'цена',
        max_digits=8,
        decimal_places=2,
    )

    class Meta:
        verbose_name = 'дополнительный ингредиент'
        verbose_name_plural = 'дополнительные ингредиенты'

    def __str__(self):
        return self.name


class Cake(models.Model):
    level = models.ForeignKey(
        Level,
        related_name='cakes',
        verbose_name='число уровней',
        on_delete=models.SET_NULL,
        null=True,
    )
    shape = models.ForeignKey(
        Shape,
        related_name='cakes',
        verbose_name='форма',
        on_delete=models.SET_NULL,
        null=True,
    )
    topping = models.ForeignKey(
        Topping,
        related_name='cakes',
        verbose_name='топпинг',
        on_delete=models.SET_NULL,
        null=True,
    )
    berries = models.ManyToManyField(
        Berry,
        related_name='cakes',
        verbose_name='ягоды',
        blank=True,
    )
    additional_ingredients = models.ManyToManyField(
        AdditionalIngredient,
        related_name='cakes',
        verbose_name='дополнительные ингредиенты',
        blank=True,
    )
    lettering = models.TextField(
        'подпись',
        null=True,
        blank=True,
        validators=[MaxLengthValidator(100)],
    )
    lettering_cost = models.FloatField(
        'цена подписи',
    )

    class Meta:
        verbose_name = 'торт'
        verbose_name_plural = 'торты'


class Customer(AbstractUser):
    phonenumber = PhoneNumberField(
        'номер телефона',
        max_length=20,
        validators=[MaxLengthValidator(12)],
    )
    address = models.CharField(
        'адрес',
        max_length=100,
    )
    social_network_link = models.TextField(
        'ссылка на соцсеть',
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = 'покупатель'
        verbose_name_plural = 'покупатели'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Order(models.Model):
    status = models.CharField(
        'статус',
        max_length=20,
        choices=STATUS,
        default='PENDING',
        db_index=True,
    )
    created_at = models.DateTimeField(
        'создан в',
        default=timezone.now,
        db_index=True,
    )
    delivered_at = models.DateTimeField(
        'доставлен в',
        blank=True,
        null=True,
        db_index=True,
    )
    delivery_time = models.DateTimeField(
        'дата и время доставки',
        db_index=True,
        blank=False,
        null=False,
    )

    comment = models.TextField(
        'комментарий к заказу',
        blank=True,
        null=True,
        validators=[MaxLengthValidator(300)],
    )
    total_price = models.DecimalField(
        'цена',
        max_digits=8,
        decimal_places=2,
    )

    customer = models.ForeignKey(
        Customer,
        related_name='orders',
        verbose_name='покупатель',
        on_delete=models.CASCADE,
    )

    cake = models.ForeignKey(
        Cake,
        related_name='orders',
        verbose_name='торт',
        on_delete=models.SET_NULL,
        null=True,
    )

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f'Заказ {self.customer.first_name} {self.customer.last_name} {self.created_at}'


class Promo(models.Model):
    title = models.CharField(
        'наименование',
        max_length=20,
        blank=True,
        null=True,
    )
    value = models.IntegerField(
        'значение',
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = 'промокоды'
        verbose_name_plural = 'промокоды'

    def __str__(self):
        return f'{self.title}'

cake/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from .models import Customer, Level, Shape, Topping, Berry, AdditionalIngredient
from django.utils import timezone


def create_elements():
    models = (Level, Shape, Topping, Berry, AdditionalIngredient)
    elements = dict()
    for model in models:
        choices = model.objects.values_list().order_by('price')
        elements[model] = choices
    return elements


def create_choices(elements, model):
    choices = []
    for choice in elements[model]:
        choices.append((f'{choice[0]} + {choice[2]}', f'{choice[1]} + {choice[2]} руб.'))
    return choices


class ConstructCakeForm(forms.Form):
    elements = create_elements()
    levels = forms.ChoiceField(label='Стоимость уровней', choices=create_choices(elements, Level), widget=forms.RadioSelect)
    shapes = forms.ChoiceField(label='Форма уровней', choices=create_choices(elements, Shape), widget=forms.RadioSelect)
    toppings = forms.ChoiceField(label='Топпинг', choices=create_choices(elements, Topping), widget=forms.RadioSelect)
    berries = forms.MultipleChoiceField(label='Ягоды', required=False, choices=create_choices(elements, Berry), widget=forms.CheckboxSelectMultiple)
    decor = forms.MultipleChoiceField(label='Декор', required=False, choices=create_choices(elements, AdditionalIngredient), widget=forms.CheckboxSelectMultiple)
    lettering = forms.CharField(label='Надпись на торте', required=False, max_length=500)


class AdvancedInfoForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    delivery_time = forms.DateTimeField(
        label='Дата доставки',
        input_formats=['%d/%m/%Y %H:%M'],
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    order_comment = forms.CharField(
        label='Комментарий к заказу',
        max_length=500,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False,
    )
    address = forms.CharField(
        label='Адрес доставки',
        max_length=500,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        initial='',
    )
    promo = forms.CharField(
        label='Промокод',
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False,
    )

    def clean_delivery_time(self):
        delivery_time = super(AdvancedInfoForm, self).clean().get('delivery_time')

        if delivery_time < timezone.now():
            raise forms.ValidationError("День доставки не может быть раньше чем сегодня.")
        return delivery_time


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

        self.fields['username'].label = 'Юзернейм'
        self.fields['username'].widget.attrs.update({'placeholder': ''})

        self.fields['password'].label = 'Пароль'
        self.fields['password'].widget.attrs.update({'placeholder': ''})


class UserCreationWithEmailForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = Customer
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'address', 'email', 'phonenumber')

    def save(self, commit=True):
        user = super(UserCreationWithEmailForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    
    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = 'Юзернейм'
        self.fields['username'].widget.attrs.update({'placeholder': ''})
        self.fields['username'].help_text = 'Обязательное поле. Только английские \
                                             буквы, цифры и символы @/./+/-/_'

        self.fields['first_name'].label = 'Имя'
        self.fields['first_name'].widget.attrs.update({'placeholder': ''})

        self.fields['last_name'].label = 'Фамилия'
        self.fields['last_name'].widget.attrs.update({'placeholder': ''})

        self.fields['address'].label = 'Адрес'
        self.fields['address'].widget.attrs.update({'placeholder': ''})

        self.fields['email'].label = 'Почта'
        self.fields['email'].widget.attrs.update({'placeholder': ''})

        self.fields['password1'].label = 'Пароль'
        self.fields['password1'].widget.attrs.update({'placeholder': ''})
        self.fields['password1'].help_text = 'Обязательное поле. От восьми символов, не только \
                                              цифры, не должен совпадать с другими полями'
        
        self.fields['password2'].label = 'Подтверждение пароля'
        self.fields['password2'].widget.attrs.update({'placeholder': ''})
        self.fields['password2'].help_text = 'Обязательное поле'

        self.fields['phonenumber'].label = 'Номер телефона'
        self.fields['phonenumber'].widget.attrs.update({'placeholder': ''})

templates/account.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
<div class="container">
    <center>
      <h2 class="text-danger">Ваши заказы</h2>
    </center>
    <hr/>
    <table class="table table-responsive">
      <tr>
        <th>Детали заказа</th>
        <th>Время заказа</th>
        <th>Время доставки</th>
        <th>Сумма заказа</th>
        <th>Статус</th>
        <th></th>
      </tr>
      {% for order in orders %}
        <tr>
          {% with cake=order.cake %}
            <td>{{ cake.level }}, {{ cake.shape }}, {{ cake.topping }}, {% for berry in cake.berries.all %}{{ berry }}, {% endfor %}{% for ingredient in cake.additional_ingredients.all %}{{ ingredient }}, {% endfor %}</td>
          {% endwith %}
          <td>{{ order.created_at }}</td>
          <td>{{ order.delivery_time }}</td>
          <td>{{ order.total_price }}</td>
          <td>{{ order.get_status_display }}</td>
          {% if order.status == 'PENDING' %}
            <td>
              <a class="btn btn-primary"  href="{% url 'cancel_order' order.id%}">Отменить</a>
            </td>
          {% endif %}
        </tr>
      {% endfor %}
    </table>
{% endblock %}

templates/adv_order_info.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block datepicker %}
     <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- XDSoft DateTimePicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

{% endblock %}

{% block content %}
<div class="row justify-content-center">
<div class="col-md-4 text-center">
    <h1 class="text-danger" align="left"> Стоимость торта - {{ cake_price }}</h1>
    <h3 class="text-dark" align="left">Если доставка в ближайшие 24 часа, то стоимость заказа будет на 20% больше. </h3>
    <form action="{% url 'index' %}">
        <div  class="page-header" id="contact" align="left">
            {% bootstrap_button button_type="submit" content="Выбрать торт заново" %}
        </div>
    </form>
<br>
<br>
<br>
<br>

    {% if not user.is_authenticated %}
        <h1 class="text-danger" align="left">Для заказа зарегистрируйтесь или войдите</h1>
            <br>
            <br>
            <div class="row" align="left">
                <div class="col text-dark">
                    <form action="{% url 'signup' %}" >
                    {% bootstrap_button button_type="submit" content="Регистрация" %}
                    </form>
                </div>

                <div class="col text-dark">
                     <form action="{% url 'login' %}" >
                     {% bootstrap_button button_type="submit" content="Вход" %}
                     </form>
                </div>
            </div>

    {% else %}
    {% bootstrap_messages %}
        <h1 class="text-danger text-center">Дополнительная информация</h1>
        <form action="{% url 'confirm' %}" method="post">
            {% csrf_token %}
            <div class="row g-3 justify-content-center">
                <div class="col-md-auto">
                <div class="mb-3">
                    <h4 class="text-dark" align="left">{{ form.delivery_time.label }}</h4>
                    {% if form.errors %}
                    {{ form.delivery_time.errors }}
                    {{ form.delivery_time }}
                    {% else %}
                    {{ form.delivery_time }}
                    {% endif %}
                </div>
                    <script>
                      $(function () {
                        $("#id_delivery_time").datetimepicker({
                          format: 'd/m/Y H:i',
                          lang:'ru'
                        });
                      });
                    </script>
                <div class="mb-3">
                    <h4 class="text-dark" align="left">{{ form.address.label }}</h4>
                    {{ form.address }}
                </div>
                <div class="mb-3">
                    <h4 class="text-dark" align="left">{{ form.order_comment.label }}</h4>
                    {{ form.order_comment }}
                </div>
                <div class="mb-3">
                    <h4 class="text-dark" align="left">{{ form.promo.label }}</h4>
                    {{ form.promo }}
                </div>
                <input class="button btn-primary" type="submit" value="Подтвердить">
            </div>
            </div>
        </form>
    {% endif %}
</div>
</div>

{% endblock %}
{% block bottom_js %}
{% endblock %}

templates/base.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Главная | BakeCake</title>
	<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" >
	<link href="{% static 'fonts/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/theme.css' %}" rel="stylesheet">
  <link href="{% static 'css/signup.css' %}" rel="stylesheet">
  {% block datepicker %}{% endblock %}

  <style type="text/css">{% block styles %}{% endblock %}</style>
</head>
<body class="container-contacts" style="padding-bottom: 100;">
{% include "header.html" %}

<div class="container-fluid pt-4">
	{% block content %}

	{% endblock content %}
</div>

{% include "footer.html" %}

{% block bottom_js %}
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock %}
</body>
</html>

templates/confirmation.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
        </div>

        <div class="col-6" >
            <br>
            <br>
            <br>
            <br>
            <br>
            <h3 class="text-dark">Стоимость торта - {{ cake_price }}</h3>
            <h3 class="text-dark">Наценка за срочный заказ - {{ surcharge }}</h3>
            {% if promo_value %}
            <h3 class="text-dark">Скидка за промокод {{ promo_value }}% - {{ discount_value }}</h3>
            {% endif %}
            <h2 class="text-danger">Общая стоимость заказа - {{ total_cake_price}}
            <div class="btn-group" role="group">
                <form action="{% url 'index' %}">
                    <div  class="page-header" id="contact">
                        {% bootstrap_button button_type="submit" content="Перейти на главную" %}

                    </div>
                </form>
            </div>
            <div class="btn-group" role="group">
                <form action="{% url 'account' %}">
                    <div  class="page-header" id="contact">
                        {% bootstrap_button button_type="submit" content="Перейти в личный кабинет" %}
                    </div>
                </form>
            </div>
        </div>
        <div class="col">
        </div>
    </div>
</div>
{% endblock %}

templates/footer.html
<footer id="footer" class="clearfix fixed-bottom">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <p>
                    <a class="fa fa-twitter footer-socialicon" target="_blank" href="https://twitter.com/"></a>
                    <a class="fa fa-facebook footer-socialicon" target="_blank" href="https://www.facebook.com/"></a>
                    <a class="fa fa-google-plus footer-socialicon" target="_blank" href="https://plus.google.com/"></a>
                    <a class="fa fa-linkedin footer-socialicon" target="_blank" href="https://instagram.com/"></a>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/header.html
{% load static %}

  <nav class="navbar navbar-expand-md navbar-light bg-light navbar-fixed-top border-0">
    <div class="container">
    	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
          data-bs-target="#navmenu">
        <span class="navbar-toggler-icon"></span>
      </button>
  			<a href="{% url 'index' %}" title="BakeCake">
            <img class="img-responsive" src="{% static 'images/logo.png' %}" alt="BakeCake"/>
        </a>
      <div class="collapse navbar-collapse" id="navmenu">
        {% if user.is_authenticated %}
          <ul class="navbar-nav navbar-right">

            <li class="nav-item">
              <a href="{% url 'index' %}" class="nav-link text-dark">
                   Добро пожаловать {{ user }} |
              </a>
            </li>

            <li class="nav-item">
              <a href="{% url 'account' %}" class="nav-link text-dark">
                  Личный кабинет |
              </a>
            </li>

            <li class="nav-item">
              <a href="{% url 'logout' %}" class="nav-link text-dark">
                  Выход
              </a>
            </li>
          </ul>
        {% else %}
          <ul class="navbar-nav navbar-right">
            <li class="nav-item">
              <a href="{% url 'login' %}" class="nav-link text-dark">
                  Вход |
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'signup' %}" class="nav-link text-dark">
                  Регистрация
              </a>
            </li>
          </ul>
        {% endif %}
    	</div>
  	</div>
	</nav>

templates/index.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<!-- Carousel -->
{% load static %}
<div class="row justify-content-center">
	<div class="col-md-9">
		<div id="theme-carousel" class="carousel slide" data-ride="carousel">
			<!-- Indicators -->
			<ol class="carousel-indicators">
				<li data-target="#theme-carousel" data-slide-to="0" class="active"></li>
				<li data-target="#theme-carousel" data-slide-to="1"></li>
				<li data-target="#theme-carousel" data-slide-to="2"></li>
			</ol>
			<!-- Wrapper for slides -->
			<div class="carousel-inner" role="listbox">
				<div class="item active">
					<img src="{% static 'images/carousel2.jpg' %}" alt="carousel2" style="width:100%" />
					<div class="carousel-caption">
					</div>
				</div>
				<div class="item">
					<img src="{% static 'images/carousel1.jpg' %}" alt="carousel1" style="width:100%" />
					<div class="carousel-caption">
					</div>
				</div>
				<div class="item">
					<img src="{% static 'images/carousel3.jpg' %}" alt="carousel3" style="width:100%">
					<div class="carousel-caption">
					</div>
				</div>
			</div>
			<!-- Controls -->
			<a class="left carousel-control" href="#theme-carousel" role="button" data-slide="prev">
		        <div class="carousel-control-arrow">&#8249;</div>
			</a>
			<a class="right carousel-control" href="#theme-carousel" role="button" data-slide="next">
		        <div class="carousel-control-arrow">&#8250;</div>
			</a>
		</div>

		<form action="{% url 'advanced_info' %}" method="post">
			{% csrf_token %}
			<div class="container-contacts">
				<div class="container">
	        <div class="page-header" id="contact">
            <h1 class=" display-3 text-danger text-center"><strong>Создай свой торт</strong></h1>
	        </div>
          <div class="row justify-content-center">
{#            <div class="col-md-4 align-self-center text-dark" style="font-size: 1.6rem;">#}

              <div class="container">
              <div class="row">
                <div class="col text-dark">
                    <h3 class="text-dark" align="left">{{ form.levels.label }}</h3>
                    <br>
                    {{ form.levels }}
                </div>
                <div class="col text-dark">
                    <h3 class="text-dark" align="left">{{ form.shapes.label }}</h3>
                    <br>
                    {{ form.shapes }}
                </div>
                <div class="col text-dark">
                    <h3 class="text-dark " align="left">{{ form.toppings.label }}</h3>
                    <br>
                    {{ form.toppings }}
                </div>
                <div class="w-100"></div>
                <div class="col text-dark">
                    <h3 class="text-dark " align="left">{{ form.berries.label }}</h3>
                    <br>
                    {{ form.berries }}
                </div>
                <div class="col text-dark">
                    <h3 class="text-dark " align="left">{{ form.lettering.label }}</h3>
                    <br>
                    <div class="container-fluid">
                    {{ form.lettering }}
                    </div>
                </div>
                <div class="col text-dark">
                    <h3 class="text-dark " align="left">{{ form.decor.label }}</h3>
                    <br>
                    {{ form.decor }}
                </div>
              </div>
            </div>
                <br>
                <br>
              <button type="submit" class="btn btn-primary btn-lg btn-block">Торт готов</button>
            </div>
	        </div>
		    </div>
		</form>
	</div>
</div>
{% endblock %}